repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
        - id: isort
          language_version: python3.8
    -
        repo: https://github.com/psf/black
        rev: 22.12.0
        hooks:
            - id: black
              args: ['--safe']
              language_version: python3.8
    -
        repo: https://github.com/pycqa/flake8
        rev: 6.0.0
        hooks:
            - id: flake8
              language_version: python3.8
              args: [
                  # E501 let black handle all line length decisions
                  # W503 black conflicts with "line break before operator" rule
                  # E203 black conflicts with "whitespace before ':'" rule
                  '--ignore=E501,W503,E203,C901']
    -
        repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
        # 2.1.1
        rev: v2.1.1
        hooks:
            - id: pydocstyle
              language_version: python3.8
              exclude: '.*(test|alembic|scripts).*'
              args: [
                 # Check for docstring presence only
                 '--select=D1',

              ]
                 # Don't require docstrings for tests
                 # '--match=(?!test).*\.py']
#    -
#        repo: https://github.com/pre-commit/mirrors-mypy
#        rev: v0.770
#        hooks:
#            -   id: mypy
#                language_version: python3.8
#                args: [--no-strict-optional, --ignore-missing-imports]
    -
        repo: https://github.com/PyCQA/pydocstyle
        rev: 6.3.0
        hooks:
          - id: pydocstyle
            language_version: python3.8
            exclude: '.*(test|alembic|scripts).*'
            #args: [
                # Don't require docstrings for tests
                #'--match=(?!test|alembic|scripts).*\.py',
            #]