FROM python:3.8-slim

RUN python -m pip install --upgrade pip
RUN python -m pip install mkdocs mkdocs-material pdocs

COPY . /opt/src

WORKDIR /opt/src

RUN python -m pip install -e \
    stac_fastapi/api \
    stac_fastapi/types \
    stac_fastapi/extensions \
    stac_fastapi/sqlalchemy


CMD ["pdocs", \
     "as_markdown", \
     "--output_dir", \
     "docs/api/", \
     "--exclude_source", \
     "--overwrite", \
     "stac_fastapi"]