FROM python:3.12-slim

# build-essential is required to build a wheel for ciso8601
RUN apt update && apt install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip

COPY . /opt/src

WORKDIR /opt/src

RUN python -m pip install \
    "stac_fastapi/types[docs]" \
    "stac_fastapi/api[docs]" \
    "stac_fastapi/extensions[docs]"

CMD ["mkdocs", "build", "-f", "docs/mkdocs.yml"]
