FROM python:3.8-slim as builder

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY . /app

RUN pip install ./stac_fastapi/types && \
    pip install ./stac_fastapi/api && \
    pip install ./stac_fastapi/extensions && \
    pip install ./stac_fastapi/sqlalchemy[server]


FROM python:3.8-slim as sqlalchemy

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

COPY --from=builder /opt/venv /opt/venv
COPY ./stac_fastapi/sqlalchemy/alembic /app/alembic
COPY ./stac_fastapi/sqlalchemy/alembic.ini /app/alembic.ini

ENV PATH="/opt/venv/bin:$PATH"

CMD ["uvicorn", "stac_fastapi.sqlalchemy.app:app", "--host", "0.0.0.0", "--port", "8080"]
