FROM python:3.8-slim as builder

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY . /app

RUN pip install ./stac_fastapi/types && \
    pip install ./stac_fastapi/api && \
    pip install ./stac_fastapi/extensions && \
    pip install ./stac_fastapi/pgstac[server]


FROM python:3.8-slim as pgstac

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

CMD ["uvicorn", "stac_fastapi.pgstac.app:app", "--host", "0.0.0.0", "--port", "8080"]
